### ISSUE TITLE
Does this work with Fivem?

### ISSUE THREAD

**Issue by MoneyTear** [alessandromrc/D3D-Hijacker#1]
Wanting to know how to get this working just like the GTA_FSR worked with Fivem is their a way or known way to get this to work with Fivem? Reshade is working fine no issues. Cannot inject or do anything while in Fivem

**Comment by alessandromrc** [comment]
I never used FiveM and will probably never use it so I got no idea about what they're doing to prevent all this.

**Comment by MoneyTear** [comment]
I think Fivem Still used ENB's so it might work i installed the GTA FSR and it seemed to have did something. Before GPU was using 6gig of Vram now its using 2.5gigs

**Comment by alessandromrc** [comment]
> I think Fivem Still used ENB's so it might work i installed the GTA FSR and it seemed to have did something. Before GPU was using 6gig of Vram now its using 2.5gigs

What I'm doing here is completely different... The dll here needs to be injected to actually swap the dll loaded from the game... the only thing you might do but might lead to a ban or whatnot is just using an injector that works on FiveM, or just replace the d3d11.dll entirely from System32 (This might lead to other issues in other games etc tho).

**Comment by alessandromrc** [comment]
Found out a trick :)

Just put the d3d11.dll inside of here:

%USERPROFILE%\AppData\Local\FiveM\FiveM.app\data\cache\subprocess

**Comment by MoneyTear** [comment]
Just to clarify this is not using the injector? Or does this still require an injector. Attempting to use the Stand Injector it does not load anything to fivem directly. Wondering what this trick is leading towards.

**Comment by alessandromrc** [comment]
> Just to clarify this is not using the injector? Or does this still require an injector. Attempting to use the Stand Injector it does not load anything to fivem directly. Wondering what this trick is leading towards.

The trick allows you to load custom renderers without using any type of injector or whatever elses... Just put the GTA_FSR dll there and load up FiveM.

**Comment by MoneyTear** [comment]
Do you think its possible the FSR code is outdated? It works in the debug view but it causes a crash on the Fivem client.  States the UI isn't able to load.  It is working correctly just not allowing it to be fully processed.

**Comment by alessandromrc** [comment]
> Do you think its possible the FSR code is outdated? It works in the debug view but it causes a crash on the Fivem client. States the UI isn't able to load. It is working correctly just not allowing it to be fully processed.

I'm not sure if FiveM devs are blocking it... do you have any stack trace maybe?

**Comment by MoneyTear** [comment]
Stack trace?

**Comment by MoneyTear** [comment]
![image_2023-12-14_153742062](https://github.com/alessandromrc/D3D-Hijacker/assets/153805128/ab4e0bd1-e774-4fac-9b0f-9ac36333cf17)

**Comment by alessandromrc** [comment]
I meant FiveM crash stack...

**Comment by MoneyTear** [comment]
Nothing as of this issue.  I'm taking another look through a few things

**Comment by MoneyTear** [comment]
![image](https://github.com/alessandromrc/D3D-Hijacker/assets/153805128/38870bed-2671-4129-a87b-565ba8b6dba8)
 Error it gave me when loading. Trying to get a crash report weird thing is I can get into a "Dedicated server" just cant do anything.  Is there any programs i should install to see the crash reports or is it the crash dump files you are looking for?

**Comment by alessandromrc** [comment]
> ![image](https://private-user-images.githubusercontent.com/153805128/290678992-38870bed-2671-4129-a87b-565ba8b6dba8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1OTUyNTEsIm5iZiI6MTcwMjU5NDk1MSwicGF0aCI6Ii8xNTM4MDUxMjgvMjkwNjc4OTkyLTM4ODcwYmVkLTI2NzEtNDEyOS1hODdiLTU2NWJhOGI2ZGJhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNFQyMzAyMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDdjMGEwMTQ5NTk2MTliNDU4ZmJmY2M4MDZkY2ZlODRkNWY0YmJhMWEyNmZjN2M3ZjQyZjRlZDcyOTMyODQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RaOlvfxWD6-FvT2KCnp8QnK62F_kyzjXxqrOYjn1oQg) Error it gave me when loading. Trying to get a crash report weird thing is I can get into a "Dedicated server" just cant do anything. Is there any programs i should install to see the crash reports or is it the crash dump files you are looking for?

Not sure ngl... I've never dealt with FiveM before.

**Comment by MoneyTear** [comment]
I've been looking into this myself and im coming up empty you are the closest contact I've had with this FSR stuff

**Comment by alessandromrc** [comment]
It is normally working for me, I'm using the last release of GTA_FSR.
![image](https://github.com/alessandromrc/D3D-Hijacker/assets/66976091/4292b201-388c-463e-8c4e-9ea4eb2eac36)

**Comment by MoneyTear** [comment]
So what I am going to do put GTA_FSR into subprocess and the dll in the sub process or do i need to put the ini file in like mods or leave it in the GTA root folder?  You were able to get it to work?

**Comment by alessandromrc** [comment]
> So what I am going to do put GTA_FSR into subprocess and the dll in the sub process or do i need to put the ini file in like mods or leave it in the GTA root folder? You were able to get it to work?

I got it to work by simply putting the content of [this](https://github.com/NarutoUA/gta5_fsr/releases/tag/1.0.4), inside:
%USERPROFILE%\AppData\Local\FiveM\FiveM.app\data\cache\subprocess

**Comment by MoneyTear** [comment]
I am going to try this again im doing a fresh clean install of gta and a new clean install of fivem. Putting both files not changing anything into %USERPROFILE%\AppData\Local\FiveM\FiveM.app\data\cache\subprocess and launching it
