### ISSUE TITLE
Failing to work!!!

### ISSUE THREAD

**Issue by Blazepoint5** [alessandromrc/D3D-Hijacker#2]
Hey bro that fsr mod for gta 5 brought me here, please can you make a tutorial or guide me through it i really want the fsr mod to work.

I downloaded the stand launchpad and library highjack.dll so whats next.
Should I add the library highjack.dll to the stand pad and inject it or do both the d3d11.dll and library highjack.dll.

I tired the d3d11.dll injection but didn't worked i guess, i hope you see this and help me.
Note: im not familiar with any of this injection, compiling and stuff, i would appreciate it if you show me step by step on how i can successfully inject the fsr mod to work. 🤝

**Comment by GravityScriptsV2** [comment]
this is a virus. i ran it through virus total and a lot of stuff popped up. also my anti virus very reputable stopped this

**Comment by alessandromrc** [comment]
> this is a virus. i ran it through virus total and a lot of stuff popped up. also my anti virus very reputable stopped this

Would love to see why my code is malware... Maybe the antivirus you think is protecting you is the actual malware ;)

**Comment by GravityScriptsV2** [comment]
Sir I don’t think virustotal or bitdefender is a virus lol

**Comment by alessandromrc** [comment]
> Sir I don’t think virustotal or bitdefender is a virus lol

And I don't think you're able to use them correctly to understand if something is a virus... 

Learn C++ and then come here and say this is a virus.

Going to close this issue as it makes no sense.
